### ISSUE TITLE
Claims not working without reason.

### ISSUE THREAD

**Issue by myagizmaktav** [supabase-community/supabase-custom-claims#7]
# Bug report

## Describe the bug

claims not working right know...

## Screenshots
![image](https://user-images.githubusercontent.com/115627863/210168425-5e1e0902-643c-4a37-ae36-dcd74a231fd5.png)
![image](https://user-images.githubusercontent.com/115627863/210168431-6f56e064-a49c-41a0-a89e-d4e1393a493f.png)
![image](https://user-images.githubusercontent.com/115627863/210168451-27e9cdfc-811d-4c21-82a5-cb150c80b37c.png)

## Description
You can see the user has app_metadata inside userrole is admin throughout photo 1.
this means claims this user has claimed userrole admin. And SQL function called set_claim is working.
The second proof is photo 2 . when you get a claim userrole with user_id is coming admin.
Photo third is RLS rules for this claims is pretty similar with docs.
The last one is in Photo 1 right corner you see data is null. 
This means My RLS rule is not pass to my user role admin claim.

**Comment by silentworks** [comment]
You haven't provided any information as to what is not working or what you have tried. This is not how you open an issue on an open source project. Please provide better title and description of the issue you are having, if possible even provide a minimal reproducable repository with the issue.
